// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APICustomerFeedbackSystem.Models;

public partial class Audit
{
    public int Id { get; set; }

    public int IdFeedback { get; set; }

    public string Last { get; set; }

    public string Now { get; set; }

    public string Tabel { get; set; }

    public string Kolom { get; set; }

    public DateOnly Tanggal { get; set; }
}