// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplicationDemo.RapidViewModels;

public partial class ViewOrderDetail
{
    public int OrderDetailId { get; set; }

    public string OrderHeaderId { get; set; }

    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public int Qty { get; set; }

    public decimal Price { get; set; }
}