// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplicationDemo.RapidViewModels;

public partial class ViewOrderHeaderInfo
{
    public string OrderHeaderId { get; set; }

    public int CustomerId { get; set; }

    public string CustomerName { get; set; }

    public string WalletName { get; set; }

    public DateTime TransactionDate { get; set; }
}