// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplicationDemo.RapidViewModels;

public partial class ViewProductsWithCategory
{
    public int ProductId { get; set; }

    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public string ProductName { get; set; }

    public int Stock { get; set; }

    public decimal Price { get; set; }
}